# Generated by Django 4.0.5 on 2022-10-21 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fijos', '0006_alter_fijos_salary_alter_historicalfijos_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalBenefits',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(verbose_name='Fecha de Creacion')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificacion')),
                ('delete_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Eliminacion')),
                ('month', models.DateField(null=True, verbose_name='Meses')),
                ('salario_basico_mensual', models.CharField(blank=True, max_length=255, null=True, verbose_name='Salario basico mensual')),
                ('salario_basico_diario', models.CharField(blank=True, max_length=255, null=True, verbose_name='salario basico diario')),
                ('utilidades_diario', models.CharField(max_length=150, verbose_name='utilidades diario')),
                ('bono_vacional_diario', models.CharField(max_length=150, verbose_name='bono vacacional diario')),
                ('salario_integral_diario', models.CharField(max_length=150, verbose_name='salario integral diario')),
                ('dias_prestaciones', models.CharField(max_length=150, verbose_name='dias de prestaciones')),
                ('apartado_mensual', models.CharField(max_length=150, verbose_name='apartado mensual bs')),
                ('anticipo', models.CharField(max_length=150, verbose_name='anticipo')),
                ('acumulado', models.CharField(max_length=150, verbose_name='acumulado')),
                ('tasa', models.CharField(max_length=150, verbose_name='tasa %')),
                ('intereses', models.CharField(max_length=150, verbose_name='intereses pagados')),
                ('intereses_prestaciones', models.CharField(max_length=150, verbose_name='intereses sobre prestaciones')),
                ('date_tasa', models.DateField(null=True, verbose_name='Fecha tasa')),
                ('datefin', models.DateField(verbose_name='Fecha')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('id_name', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fijos.fijos', verbose_name='name')),
            ],
            options={
                'verbose_name': 'historical Modelo Base',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Benefits',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(verbose_name='Fecha de Creacion')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('delete_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminacion')),
                ('month', models.DateField(null=True, verbose_name='Meses')),
                ('salario_basico_mensual', models.CharField(blank=True, max_length=255, null=True, verbose_name='Salario basico mensual')),
                ('salario_basico_diario', models.CharField(blank=True, max_length=255, null=True, verbose_name='salario basico diario')),
                ('utilidades_diario', models.CharField(max_length=150, verbose_name='utilidades diario')),
                ('bono_vacional_diario', models.CharField(max_length=150, verbose_name='bono vacacional diario')),
                ('salario_integral_diario', models.CharField(max_length=150, verbose_name='salario integral diario')),
                ('dias_prestaciones', models.CharField(max_length=150, verbose_name='dias de prestaciones')),
                ('apartado_mensual', models.CharField(max_length=150, verbose_name='apartado mensual bs')),
                ('anticipo', models.CharField(max_length=150, verbose_name='anticipo')),
                ('acumulado', models.CharField(max_length=150, verbose_name='acumulado')),
                ('tasa', models.CharField(max_length=150, verbose_name='tasa %')),
                ('intereses', models.CharField(max_length=150, verbose_name='intereses pagados')),
                ('intereses_prestaciones', models.CharField(max_length=150, verbose_name='intereses sobre prestaciones')),
                ('date_tasa', models.DateField(null=True, verbose_name='Fecha tasa')),
                ('datefin', models.DateField(verbose_name='Fecha')),
                ('id_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fijos.fijos', verbose_name='name')),
            ],
            options={
                'verbose_name': 'Modelo Base',
                'verbose_name_plural': 'Modelos Base',
                'abstract': False,
            },
        ),
    ]
