# Generated by Django 4.0.5 on 2022-11-11 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefits',
            name='apartado_mensual',
            field=models.IntegerField(max_length=150, verbose_name='apartado mensual bs'),
        ),
        migrations.AlterField(
            model_name='historicalbenefits',
            name='apartado_mensual',
            field=models.IntegerField(max_length=150, verbose_name='apartado mensual bs'),
        ),
    ]
