# Generated by Django 4.0.5 on 2022-11-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0002_alter_benefits_apartado_mensual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefits',
            name='acumulado',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='acumulado'),
        ),
        migrations.AlterField(
            model_name='benefits',
            name='anticipo',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='anticipo'),
        ),
        migrations.AlterField(
            model_name='benefits',
            name='apartado_mensual',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='apartado mensual bs'),
        ),
        migrations.AlterField(
            model_name='benefits',
            name='bono_vacional_diario',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='bono vacacional diario'),
        ),
        migrations.AlterField(
            model_name='benefits',
            name='dias_prestaciones',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='dias de prestaciones'),
        ),
        migrations.AlterField(
            model_name='benefits',
            name='intereses',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='intereses pagados'),
        ),
        migrations.AlterField(
            model_name='benefits',
            name='intereses_prestaciones',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='intereses sobre prestaciones'),
        ),
        migrations.AlterField(
            model_name='benefits',
            name='salario_basico_diario',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='salario basico diario'),
        ),
        migrations.AlterField(
            model_name='benefits',
            name='salario_basico_mensual',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='Salario basico mensual'),
        ),
        migrations.AlterField(
            model_name='benefits',
            name='salario_integral_diario',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='salario integral diario'),
        ),
        migrations.AlterField(
            model_name='benefits',
            name='tasa',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='tasa %'),
        ),
        migrations.AlterField(
            model_name='benefits',
            name='utilidades_diario',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='utilidades diario'),
        ),
        migrations.AlterField(
            model_name='historicalbenefits',
            name='acumulado',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='acumulado'),
        ),
        migrations.AlterField(
            model_name='historicalbenefits',
            name='anticipo',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='anticipo'),
        ),
        migrations.AlterField(
            model_name='historicalbenefits',
            name='apartado_mensual',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='apartado mensual bs'),
        ),
        migrations.AlterField(
            model_name='historicalbenefits',
            name='bono_vacional_diario',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='bono vacacional diario'),
        ),
        migrations.AlterField(
            model_name='historicalbenefits',
            name='dias_prestaciones',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='dias de prestaciones'),
        ),
        migrations.AlterField(
            model_name='historicalbenefits',
            name='intereses',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='intereses pagados'),
        ),
        migrations.AlterField(
            model_name='historicalbenefits',
            name='intereses_prestaciones',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='intereses sobre prestaciones'),
        ),
        migrations.AlterField(
            model_name='historicalbenefits',
            name='salario_basico_diario',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='salario basico diario'),
        ),
        migrations.AlterField(
            model_name='historicalbenefits',
            name='salario_basico_mensual',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='Salario basico mensual'),
        ),
        migrations.AlterField(
            model_name='historicalbenefits',
            name='salario_integral_diario',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='salario integral diario'),
        ),
        migrations.AlterField(
            model_name='historicalbenefits',
            name='tasa',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='tasa %'),
        ),
        migrations.AlterField(
            model_name='historicalbenefits',
            name='utilidades_diario',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='utilidades diario'),
        ),
    ]
