# Generated by Django 4.0.5 on 2022-11-18 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0004_benefits_bono_frac_benefits_vacaciones_frac_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benefits',
            name='bono_frac',
        ),
        migrations.RemoveField(
            model_name='benefits',
            name='vacaciones_frac',
        ),
        migrations.RemoveField(
            model_name='historicalbenefits',
            name='bono_frac',
        ),
        migrations.RemoveField(
            model_name='historicalbenefits',
            name='vacaciones_frac',
        ),
    ]
