# Generated by Django 4.0.5 on 2022-11-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0005_remove_benefits_bono_frac_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefits',
            name='antiguedad',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='antiguedad del empleado'),
        ),
        migrations.AddField(
            model_name='historicalbenefits',
            name='antiguedad',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='antiguedad del empleado'),
        ),
    ]
