# Generated by Django 4.0.5 on 2022-06-12 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(verbose_name='Fecha de Creacion')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('delete_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminacion')),
                ('operations', models.CharField(max_length=150, unique=True, verbose_name='Operaciones')),
                ('marketing', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mercadeo')),
                ('sales', models.CharField(max_length=150, unique=True, verbose_name='Ventas')),
                ('finance', models.CharField(max_length=150, unique=True, verbose_name='Finanzas')),
                ('human_Resources', models.CharField(max_length=150, unique=True, verbose_name='Recursos Humanos')),
            ],
            options={
                'verbose_name': 'Modelo Base',
                'verbose_name_plural': 'Modelos Base',
                'abstract': False,
            },
        ),
    ]
