# Generated by Django 4.0.5 on 2022-06-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='finance',
            field=models.CharField(max_length=150, unique=True, verbose_name='Departamento Finanzas'),
        ),
        migrations.AlterField(
            model_name='department',
            name='human_Resources',
            field=models.CharField(max_length=150, unique=True, verbose_name='Departamento Recursos Humanos'),
        ),
        migrations.AlterField(
            model_name='department',
            name='marketing',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Departamento Mercadeo'),
        ),
        migrations.AlterField(
            model_name='department',
            name='operations',
            field=models.CharField(max_length=150, unique=True, verbose_name='Departamento Operaciones'),
        ),
        migrations.AlterField(
            model_name='department',
            name='sales',
            field=models.CharField(max_length=150, unique=True, verbose_name='Departamento Ventas'),
        ),
    ]
