# Generated by Django 4.0.5 on 2022-07-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fijos', '0003_fijos_historicalfijos_delete_fijo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fijos',
            name='date',
            field=models.DateField(null=True, verbose_name='Fecha de ingreso'),
        ),
        migrations.AddField(
            model_name='historicalfijos',
            name='date',
            field=models.DateField(null=True, verbose_name='Fecha de ingreso'),
        ),
    ]
