# Generated by Django 4.0.5 on 2022-10-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fijos', '0004_fijos_date_historicalfijos_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fijos',
            name='salary',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Salario'),
        ),
        migrations.AddField(
            model_name='historicalfijos',
            name='salary',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Salario'),
        ),
    ]
