# Generated by Django 4.0.5 on 2022-10-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fijos', '0005_fijos_salary_historicalfijos_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fijos',
            name='salary',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='Salario'),
        ),
        migrations.AlterField(
            model_name='historicalfijos',
            name='salary',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='Salario'),
        ),
    ]
