# Generated by Django 4.0.5 on 2022-10-30 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fijos', '0006_alter_fijos_salary_alter_historicalfijos_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fijos',
            name='num',
        ),
        migrations.RemoveField(
            model_name='historicalfijos',
            name='num',
        ),
    ]
