# Generated by Django 4.0.5 on 2022-11-16 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fijos', '0007_remove_fijos_num_remove_historicalfijos_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fijos',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='historicalfijos',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nombre'),
        ),
    ]
