# Generated by Django 4.0.5 on 2022-11-19 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fijos', '0010_fijos_utilidades_historicalfijos_utilidades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fijos',
            name='bono_frac',
        ),
        migrations.RemoveField(
            model_name='fijos',
            name='vacaciones_frac',
        ),
        migrations.RemoveField(
            model_name='historicalfijos',
            name='bono_frac',
        ),
        migrations.RemoveField(
            model_name='historicalfijos',
            name='vacaciones_frac',
        ),
        migrations.AddField(
            model_name='fijos',
            name='dias_frac',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='dias vacaciones fraccionadas'),
        ),
        migrations.AddField(
            model_name='fijos',
            name='total_utilidades',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='total utilidades fraccionadas'),
        ),
        migrations.AddField(
            model_name='fijos',
            name='total_vacaciones_frac',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='total vacaciones fraccionadas'),
        ),
        migrations.AddField(
            model_name='historicalfijos',
            name='dias_frac',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='dias vacaciones fraccionadas'),
        ),
        migrations.AddField(
            model_name='historicalfijos',
            name='total_utilidades',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='total utilidades fraccionadas'),
        ),
        migrations.AddField(
            model_name='historicalfijos',
            name='total_vacaciones_frac',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='total vacaciones fraccionadas'),
        ),
        migrations.AlterField(
            model_name='fijos',
            name='utilidades',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='utilidades fraccionadas'),
        ),
        migrations.AlterField(
            model_name='historicalfijos',
            name='utilidades',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='utilidades fraccionadas'),
        ),
    ]
