# Generated by Django 4.0.5 on 2022-06-12 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historical', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historical',
            name='finance',
        ),
        migrations.RemoveField(
            model_name='historical',
            name='human_Resources',
        ),
        migrations.RemoveField(
            model_name='historical',
            name='marketing',
        ),
        migrations.RemoveField(
            model_name='historical',
            name='sales',
        ),
    ]
