# Generated by Django 4.0.5 on 2022-06-26 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hired', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hired',
            name='CI',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cedula'),
        ),
        migrations.AddField(
            model_name='historicalhired',
            name='CI',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cedula'),
        ),
    ]
