# Generated by Django 4.0.5 on 2022-06-10 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(verbose_name='Fecha de Creacion')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('delete_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminacion')),
                ('coordinator_humans', models.CharField(max_length=150, unique=True, verbose_name='Coordinador recursos humanos')),
                ('consultant', models.CharField(blank=True, max_length=255, null=True, verbose_name='Consulor')),
                ('programmer', models.CharField(max_length=150, unique=True, verbose_name='Programador')),
                ('analyst_finance', models.CharField(max_length=150, unique=True, verbose_name='Analista de finanzas')),
                ('technical_support', models.CharField(max_length=150, unique=True, verbose_name='Soporte tecnico')),
                ('manager', models.CharField(max_length=150, unique=True, verbose_name='Gerente')),
                ('coordinator', models.CharField(max_length=150, unique=True, verbose_name='Coordinador')),
            ],
            options={
                'verbose_name': 'Modelo Base',
                'verbose_name_plural': 'Modelos Base',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalCargo',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(verbose_name='Fecha de Creacion')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificacion')),
                ('delete_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Eliminacion')),
                ('coordinator_humans', models.CharField(db_index=True, max_length=150, verbose_name='Coordinador recursos humanos')),
                ('consultant', models.CharField(blank=True, max_length=255, null=True, verbose_name='Consulor')),
                ('programmer', models.CharField(db_index=True, max_length=150, verbose_name='Programador')),
                ('analyst_finance', models.CharField(db_index=True, max_length=150, verbose_name='Analista de finanzas')),
                ('technical_support', models.CharField(db_index=True, max_length=150, verbose_name='Soporte tecnico')),
                ('manager', models.CharField(db_index=True, max_length=150, verbose_name='Gerente')),
                ('coordinator', models.CharField(db_index=True, max_length=150, verbose_name='Coordinador')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Modelo Base',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
